### ISSUE TITLE
Please check the capability type in FrequencyPowersProvider.getCapability

### ISSUE THREAD

**Issue by thexaero** [WithoutAMods/WithoutARedstone#1]
I have received a report of a compatibility issue between your mod and mine. I think I have figured out the problem.

You need to make sure that the capability type requested from _FrequencyPowersProvider_ is actually _CapabilityFrequencyPowers.FREQUENCY_POWERS_CAPABILITY_ before returning your capability. The _getCapability_ method in your capability provider is actually called for all capability types that reach your provider, not just those registered by your mod. When the type is not _CapabilityFrequencyPowers.FREQUENCY_POWERS_CAPABILITY_, then you are overwriting the correct capability with your own. This breaks my mod and should break a lot of other mods that use capabilities. You need to return _LazyOptional.empty()_ for unrecognized capability types.

Thanks in advance!

**Comment by WithoutAName25** [comment]
Thanks for the issue report and the detailed description. It will be fixed in version 1.16.5-1.0.1.
