### ISSUE TITLE
Compatibility with ProjectRed/CBMultipart

### ISSUE THREAD

**Issue by DisplayPort** [WithoutAMods/WithoutARedstone#2]
**Is your feature request related to a problem? Please describe.**
When trying to power a Wireless Link using Red Alloy no signal is sent to the Wireless Link, receiving using Red Alloy however works fine.

**Describe the solution you'd like**
Make it possible for Red Alloy and other modded redstone items to send a signal to the Wireless Link.

**Additional context**
Example showing problem:
![2021-08-27_05 59 29](https://user-images.githubusercontent.com/44052080/131069989-edcc2570-a088-4804-a627-35d3f6d2ef58.png)

**Comment by WithoutAName25** [comment]
Fixed in v1.0.3

**Comment by DisplayPort** [comment]
Wow that was fast, epic.

**Comment by WithoutAName25** [comment]
It wasn't complicated to fix, but I didn't know it was a problem before.
